import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import io from 'socket.io-client'

let socket

const Home: NextPage = () => {
  const [input, setInput] = useState('')

  useEffect(() => {
    const socketInitializer = async () => {
      await fetch('/api/socket')
      socket = io()

      socket.on('connect', () => {
        console.log('✅ connected to server')
      })

      socket.on('update-input', msg => {
        setInput(msg)
      })

      return function cleanUp () {
        socket.close()
      }
    }
    socketInitializer()
  }, [])

  const onChangeHandler = e => {
    setInput(e.target.value)
    socket.emit('input-change', e.target.value)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className={'text-3xl'}>tic tac toe</h1>
        <div className='relative w-100 mx-auto'>
          <input
            placeholder='Type something'
            value={input}
            onChange={onChangeHandler}
          />
        </div>
      </main>
    </div>
  )
}

export default Home
